# 사이트 공통 설정
BASE_URL = "https://dongjak-massage.pages.dev"

BRAND = "간다 GO"
PHONE = "0508-202-4719"
PHONE_DISPLAY = "0508-202-4719"

# 상단 메뉴 — 하위 메뉴에는 키워드를 반복하지 않고 지역명·역명만 표시한다.
NAV = [
    ("홈", "/", []),
    ("동작 출장마사지", "/massage/", [
        ("출장마사지 안내", "/massage/#service"),
        ("홈타이 안내", "/massage/#hometai"),
        ("전지역 방문 안내", "/massage/#coverage"),
        ("지하철역 인근 안내", "/massage/#stations"),
        ("예약 가능 시간", "/massage/#hours"),
        ("코스 선택 안내", "/massage/#course"),
        ("이용 전 확인사항", "/massage/#check"),
        ("위생·안전 안내", "/massage/#safety"),
        ("자주 묻는 질문", "/massage/#faq"),
    ]),
    ("지역별 안내", "/dongjak-gu/", [
        ("동작구 전체", "/dongjak-gu/"),
        ("노량진동", "/dongjak-gu/noryangjin-dong/"),
        ("상도동", "/dongjak-gu/sangdo-dong/"),
        ("본동", "/dongjak-gu/bon-dong/"),
        ("흑석동", "/dongjak-gu/heukseok-dong/"),
        ("동작동", "/dongjak-gu/dongjak-dong/"),
        ("사당동", "/dongjak-gu/sadang-dong/"),
        ("대방동", "/dongjak-gu/daebang-dong/"),
        ("신대방동", "/dongjak-gu/sindaebang-dong/"),
    ]),
    ("지하철역별 안내", "/dongjak-gu/stations/", [
        ("역 전체", "/dongjak-gu/stations/"),
        ("노량진역", "/dongjak-gu/stations/noryangjin-station/"),
        ("대방역", "/dongjak-gu/stations/daebang-station/"),
        ("노들역", "/dongjak-gu/stations/nodeul-station/"),
        ("흑석역", "/dongjak-gu/stations/heukseok-station/"),
        ("동작역", "/dongjak-gu/stations/dongjak-station/"),
        ("이수역", "/dongjak-gu/stations/isu-station/"),
        ("사당역", "/dongjak-gu/stations/sadang-station/"),
        ("남성역", "/dongjak-gu/stations/namseong-station/"),
        ("숭실대입구역", "/dongjak-gu/stations/soongsil-univ-station/"),
        ("상도역", "/dongjak-gu/stations/sangdo-station/"),
        ("장승배기역", "/dongjak-gu/stations/jangseungbaegi-station/"),
        ("신대방삼거리역", "/dongjak-gu/stations/sindaebang-samgeori-station/"),
        ("보라매역", "/dongjak-gu/stations/boramae-station/"),
        ("서울지방병무청역", "/dongjak-gu/stations/seoul-regional-military-manpower-station/"),
        ("보라매공원역", "/dongjak-gu/stations/boramae-park-station/"),
        ("보라매병원역", "/dongjak-gu/stations/boramae-hospital-station/"),
    ]),
    ("테마별 안내", "/themes/", [
        ("전체 테마", "/themes/"),
        ("스웨디시", "/themes/swedish/"),
        ("로미로미", "/themes/lomilomi/"),
        ("타이마사지", "/themes/thai/"),
        ("중국마사지", "/themes/chinese/"),
        ("아로마테라피", "/themes/aroma/"),
        ("홈케어", "/themes/homecare/"),
        ("호텔식마사지", "/themes/hotel-style/"),
        ("발마사지", "/themes/foot/"),
        ("스포츠·경락", "/themes/sports/"),
        ("스킨케어", "/themes/skincare/"),
        ("왁싱", "/themes/waxing/"),
        ("커플 관리", "/themes/couple/"),
        ("24시간", "/themes/24hours/"),
        ("수면 가능", "/themes/overnight/"),
    ]),
    ("코스안내", "/courses/", [
        ("전체 코스", "/courses/"),
        ("피로 회복 관리", "/courses/#recovery"),
        ("아로마 관리", "/courses/#aroma"),
        ("스포츠 관리", "/courses/#sports"),
        ("홈타이 코스", "/courses/#hometai"),
        ("커플·가족 방문 관리", "/courses/#couple"),
        ("기업·단체 방문 관리", "/courses/#group"),
        ("가격 안내", "/courses/#price"),
        ("코스 선택 가이드", "/courses/#guide"),
    ]),
    ("예약안내", "/reservation/", [
        ("예약 방법", "/reservation/#how"),
        ("예약 가능 시간", "/reservation/#hours"),
        ("방문 가능 장소", "/reservation/#place"),
        ("결제 안내", "/reservation/#payment"),
        ("변경·취소 안내", "/reservation/#change"),
        ("예약 전 체크사항", "/reservation/#check"),
    ]),
    ("이용가이드", "/guide/", [
        ("처음 이용하시는 분", "/guide/#first"),
        ("방문 전 준비사항", "/guide/#prepare"),
        ("위생 및 안전 기준", "/guide/#hygiene"),
        ("관리 후 주의사항", "/guide/#after"),
        ("금지행위 안내", "/guide/#prohibited"),
        ("이용 FAQ", "/guide/#faq"),
    ]),
    ("매거진", "/magazine/", [
        ("전체 글", "/magazine/"),
        ("아로마 오일 고르기", "/magazine/aroma-oil-guide/"),
        ("야간 근무 회복법", "/magazine/night-shift-recovery/"),
        ("수험 기간 컨디션", "/magazine/exam-season-care/"),
        ("둘이 함께 받기", "/magazine/couple-home-care/"),
        ("홈타이 용어 정리", "/magazine/hometai-glossary/"),
        ("서서 일하는 발 관리", "/magazine/standing-job-foot-care/"),
    ]),
    ("후기", "/reviews/", [
        ("전체 후기", "/reviews/"),
        ("지역별 후기", "/reviews/#area"),
        ("역세권 후기", "/reviews/#station"),
        ("후기 작성 안내", "/reviews/#write"),
    ]),
    ("고객센터", "/support/", [
        ("공지사항", "/support/#notice"),
        ("자주 묻는 질문", "/support/#faq"),
        ("1:1 문의", "/support/#contact"),
        ("제휴·기업 문의", "/support/#biz"),
        ("개인정보처리방침", "/support/privacy/"),
        ("이용약관", "/support/terms/"),
    ]),
]
